import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { global } from 'styled-jsx/css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main'>
          
        <div className={styles.center}>
          <Image
            className='logo'
            src="/naboo.png"
            alt="NabooLogo"
            width={475}
            height={120}
            priority
          />
          {/* <div className={styles.thirteen}>
            <Image
              src="/naboo.png"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div> */}
        </div>
        <div className={styles.subtitle}>
            <h2 className={inter.className}>
              Aqui você encontra tudo o que precisa para ter sucesso em nossas ferramentas
            </h2>
        </div>


        <div className={styles.grid}>
            <a
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 className={inter.className}>
                Videoaulas
              </h2>
              <p className={inter.className}>
                Acesse agora videoaulas para você aprender definitivamente todas as funcionalidades da plataforma, aulas separadas por módulos
              </p>
              <button className={styles.accessButton}>
                <i className={inter.className}>
                  ACESSAR
                </i>
              </button>
            </a>

          <a
            href=""
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Materiais 
            </h2>
            <p className={inter.className}>
              Acesse agora materiais sobre o sistema, onde você irá tirar suas dúvidas e conhecer melhor as funcionalidades do módulo que você deseja.
            </p>
            <button className={styles.accessButton}>
              <i className={inter.className}>
                ACESSAR
              </i>
            </button>

          </a>

          <a
            href=""
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Treinamentos
            </h2>
            <p className={inter.className}>
              Agende agora um treinamento para o módulo que você deseja e nossa equipe entrará em contato, para realizar seu treinamento e tirar todas suas dúvidas de maneira especializada.
            </p>
            <button className={styles.accessButton}>
              <i className={inter.className}>
                ACESSAR
              </i>
            </button>

          </a>

          <a
            href=""
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Supporte 
            </h2>
            <p className={inter.className}>
              Acesse agora videoaulas para você aprender definitivamente todas as funcionalidades da plataforma, aulas separadas por módulos
            </p>
            <button className={styles.accessButton}>
              <i className={inter.className}>
                ACESSAR
              </i>
            </button>

          </a>
        </div>
        <div className={styles.footer}></div>
      </main>
    </>
  )
}
